### ISSUE TITLE
Issue while trying to use Mass Update tool

### ISSUE THREAD

**Issue by israeltamariz1** [PagerDuty/public-support-scripts#117]
Tried to use the MASS update tool, but there was a Not Found library issue for pdpyras object, could you please help us to fix it? Thanks.

**Comment by DanJeffs** [comment]
Hi, 
Just tested and all looks ok at the moment. 
Tested with Python 3.11.2
Have you installed the Python requirements? - https://github.com/PagerDuty/public-support-scripts/tree/master#python-scripts
